### ISSUE TITLE
FnOS无法启动容器

### ISSUE THREAD

**Issue by OcrSu** [kkkgo/caddy-docker#1]
![image](https://github.com/user-attachments/assets/88fc9787-8e0a-4cfe-8144-bdbfafda1e29)
![image](https://github.com/user-attachments/assets/c703a830-5672-4673-8ab6-713f042e650c)

**Comment by kkkgo** [comment]
日志已经告诉你了，你的/vol2/1000/Configs/Caddy目录下没有caddyfile.txt文件。

**Comment by OcrSu** [comment]
> 日志已经告诉你了，你的/vol2/1000/Configs/Caddy目录下没有caddyfile.txt文件。

原来如此，看来眼睛要好好治治了，我一直以为容器里配置文件会自动生成一个，然后挂载data后，会有的。

多谢！
